 
Liste des tableaux : <br />
<table>
	<tr>
		<td>Id</td>
		<td>Titre</td>
		<td>Description</td>
		<td>Prix</td>
		<td>Theme</td>
		<td>Date publication</td>
		<td>Active</td>
		<td>Image</td>
	</tr>
    <?php foreach ($this->entries as $entry): ?>
	<tr>
   	 <td><?php echo $this->escape($entry->article_id) ?></td>
	    <td><?php echo $this->escape($entry->titre) ?></td>
	    <td><?php echo $this->escape($entry->description) ?></td>
	    <td><?php echo $this->escape($entry->prix) ?></td>
	    <td><?php echo $this->escape($entry->datepublication) ?></td>
	    <td><?php echo $this->escape($entry->active) ?></td>
	    <td><img width="300px" src="/tableaux/<?php echo $this->escape($entry->image) ?>" /></td>
	</tr>
    <?php endforeach ?>
</table>