<div>
	<ul class="thumbnails">
	<?php 
	$i=0;
	foreach ($this->paginator as $article) 
		{
		$i++;?>
		<li class="span3">
				<div class="thumbnail">
					<img src="/tableaux/<?php echo $article['image'];?>" />
					
					<h5><?php echo $article['titre'];?></h5>
					<a class='btn btn-success btn-mini' href='<?php $this->linkTo('ajouter','panier','default', array('id'=>$article['article_id']));?>'>
						<i class='icon-shopping-cart icon-white'></i> Ajouter au caddie
					</a>
					<br />
					<a class='btn btn-primary btn-mini' href='/tableau/<?php echo $article['article_id'];?>'><i class='icon-eye-open icon-white'></i>Détails</a>
				</div>
			</li>
		 
	<?php	} ?>
	</ul>
<?php echo $this->paginationControl($this->paginator,'sliding','pagination.phtml');
	?>
</div>