<h1 style="float:none;" >User</h1>
<!--feedback bar -->
<div class="feedback-bar" id="feedback-top" style="display:none;">
</div>
<!--feedback bar - END -->
<div>
<form id="UserForm" enctype="application/x-www-form-urlencoded" method="post" action="/admin/user/form">
    <div>
    <table cellpadding="0" cellspacing="0" >
        
        <tr>
            <td><?php echo $this->Sr("admin_user_form-email"); ?></td>
            <td><input name="email" id="email" class="required" value="<?php echo $this->user->user_email; ?>" type="text" /></td>
        </tr>
        <tr id="pass-tr" style="display: none;">
            <td><?php echo $this->Sr("admin_user_form-password"); ?></td>
            <td id="input-password"><input name="password" id="password" value="" type="password" /></td>
        </tr>
        
        
        
        <?php if($this->user) { ?>
            <tr id="change-tr">
                <td>&nbsp;</td>
                <td><a onclick="javascript: $('#pass-tr').show();$('#password').attr('name','password');$('#change-tr').hide()"> Change Password </a></td><td>
                </td>
            </tr>
        <?php } ?>
        <?php if($this->super_admin) { ?>
            <?php if($this->user->user_role <> 5){ ?>
            <tr>
                <td><?php echo $this->Sr("admin_user_form-cms_access"); ?></td>
                <td>
                    <?php echo $this->formSelect('cms_access_role', $this->user->user_role, array("id"=>'cms_access_role', 'class'=>"cms-access-role-select"), $this->roles);?>
                </td>
            </tr>
            <?php } else {?>
            <tr>
                <td><input type="hidden" value="5" name="cms_access_role"/></td>
                <td>This is a super Admin user, to change the permission of this user please go to the database directly.</td>
            </tr>
            <?php } ?>
        <?php } ?>

    </table>
    </div>
    <div id="extra-info">
        <h2>Extra Info</h2>
        <?php echo $this->action('display-fields','user','admin',array("user_id" => $this->user->user_id)); ?>
    </div>
    
<input type="hidden" name="user_id" value="<?php echo $this->user->user_id; ?>"/>
</form>

<button id="save-form" class="grey-button">Save</button>
</div>
<!-- form - END -->

<script>


$(document).ready(function() {
    
    
    $('#save-form').click(function() {
        
          $.post("/admin/user/form", $("#UserForm").serialize() ,
               function(data) {
                    $("#feedback-top").html(data);
                    $("#feedback-top").slideDown();
               });        
    });
    
    
});

</script>