<div>
	<p>View script for controller <b>Article</b> and script/action name <b>index</b></p>
	<?php
	
	echo "<ul class=\"thumbnails\">";
	$i=0;
	foreach ($this->paginator as $article) 
		{
		$i++;
		echo"
			<li class=\"span3\">
				<div class=\"thumbnail\">
					<img src=\"http://lorempixel.com/260/180/abstract/".$i."\" alt=\"\">
					
					<h5>".$article['titre']."</h5>
					<p>Thumbnail caption right here...</p>
					<a class='btn btn-success btn-mini' href='".$this->linkTo('ajouter','panier','default',array('id'=>$article['article_id']))."'><i class='icon-shopping-cart icon-white'></i> Ajouter</a>
					<a class='btn btn-primary btn-mini' href=''><i class='icon-eye-open icon-white'></i>Détails</a>
				</div>
			</li>
		";
		}
	echo "</ul>";
	echo $this->paginationControl($this->paginator,'sliding','pagination.phtml');
	?>
</div>