
<div class="banner_title">
</div>


<div class="row">
	<div class="span4">
		<?php echo $loginForm = $this->loginForm; ?>
	</div>	
	<div class="span4 well">
		<p class="badge badge-warning">Vous souhaitez cr&eacute;er un compte</p>
		<p>Cr&eacute;er un compte vous permettra de passer et suivre vos commandes</p>
		<a class="btn btn-primary" href="<?php echo $this->linkTo('inscription','compte') ?>">Cr&eacute;er un compte maintenant</a>
	</div>
</form>	