<div>
	<p>View script for controller <b>Article</b> and script/action name <b>index</b></p>
	<?php
	
	echo "<ul class=\"thumbnails\">";
	$i=0;
	foreach ($this->paginator as $article) 
		{
		$i++;
		echo"
			<li class=\"span3\">
				<div class=\"thumbnail\">
					<img src=\"http://lorempixel.com/260/180/abstract/".$i."\" alt=\"\">
					
					<h5>".$article['nom']."</h5>
					<p>Thumbnail caption right here...</p>
				</div>
			</li>
		";
		}
	echo "</ul>";
	echo $this->paginationControl($this->paginator,'sliding','pagination.phtml');
	?>
</div>