<link rel="stylesheet" href="/css/admin.css" type="text/css" >
<table border="0" cellspacing="0" cellpadding="0" id="login-form" align="center">
    <tr>
        <td>
            <div id="content-login">
                <!-- Dynamic Area Begin -->
                <!-- Title Page -->
                <h1><img class="img-logo-login" src="/images/admin/logo-login.png" title="ZillerCMS" alt="ZillerCMS" /></h1>

                <form enctype="application/x-www-form-urlencoded" method="post" action="/admin/login/">
                    <dl class="zend_form">
                        <dt id="user_name-label"><label for="user_name" class="optional">Login:</label></dt>
                        <dd id="user_name-element">
                            <input type="text" name="user_name" id="user_name" value=""></dd>
                        <dt id="user_password-label"><label for="user_password" class="optional">Password:</label></dt>
                        <dd id="user_password-element">
                            <input type="password" name="user_password" id="user_password" value=""></dd>
                        <dt id="add-label">&nbsp;</dt>
                        <dd id="add-element">
                            <input type="submit" name="add" id="add" value="Login"></dd>
                    </dl>
                </form>           

                <div class="clear"></div>           
                <!-- Dynamic Area End -->      
                <?php if ($this->message) { ?>
                    <div class="error-message">Uh-oh... Invalid Login credentials. Please try again.</div>
                <?php } ?>
            </div>
        </td>
    </tr>
    <tr>
        <td colspan="2"><div class="align-right login-footer">CMS Developed by:<a href="http://www.ziller.com.au/"> Ziller Web Solutions</a></div>
            <div class="clear"></div></td>
    </tr>
</table>