<div class="sign-up-prompt-A-container-inline" id="sign-up-prompt-inline">
    <div class="sign-up-prompt-A-inline">
    <h2 class="sign-up-inline">Welcome to Ollio!</h2><p>Personalize Ollio with the stores and products you love. <a id="action-log-in-welcomebar" href="/login/display-login" title="Log in">Log in</a> or</p><a class="button-yellow" id="action-sign-up-welcomebar" href="/login/display-login" title="Sign Up">Sign Up</a>
    <div class="sign-up-prompt-hide-container">
    <a id="action-close-welcomebar" href="#" title="Hide this message"><span class="button-close-icon"></span></a>
    </div>
    <div class="clear"></div>
    </div>
    <div class="clear"></div>
</div>