<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php 
	echo $this->headTitle();
    echo $this->headLink();
    echo $this->headLink()->appendStylesheet('/css/style.css')
	?>
	<link rel="stylesheet/less" href="/less/bootstrap.less">
    <link rel="icon" type="image/gif" href="/img/favicon.png"/>
	<script type="text/javascript" src="/js/less.js"></script>
</head>
<body>
	<!--TopBar-->
	<div class="navbar">
		<div class="navbar-inner">
			<div class="container">
				<div class='pull-left'>
					<span class="badge badge-warning">&nbsp;&nbsp;</span>
					<span class="badge badge-success">&nbsp;&nbsp;</span>
					<span class="badge badge-info">&nbsp;&nbsp;</span>
					<span class="badge badge-important">&nbsp;&nbsp;</span>
					<span class="badge badge-defaut">&nbsp;&nbsp;</span>
					<h3><a><em>Sur la toile</em></a></h3>
				</div>
				
				<?php 
				if($this->loggedUser) {
					$this->loggedin->findById('nav-panier')->set('qteArticle',$this->qteArticle);
					$this->loggedin->findById('nav-compte')->set('label', $this->loggedUser->email);
					$this->loggedin->findById('nav-compte')->set('logged','');
					echo $this->navigation()->menu()->setPartial(array('commun/menu.phtml','default'))->render($this->loggedin);
					if($this->loggedUser->role_id == Model_Utilisateur::_ROLE_SUPER_ADMIN){
						echo $this->navigation()->menu()->render($this->admin);
					} 
				}else{
					$this->loggedout->findById('signup');
					echo $this->navigation()->menu()->setPartial(array('commun/menu.phtml','default'))->render($this->loggedout);
				}
				?>
				<form class="navbar-search pull-right">
					<i class="icon-search icon-white"></i>
					<input type="text" class="search-query" placeholder="rechercher">
				</form>
				<?php echo $this->navigation()->menu()->setUlClass('nav pull-right')->render($this->base); ?>
			</div>
		</div>
	</div>
    <div class="container">
	 
		<div class="row">
			<!--LeftBar-->
			<div class="span3">
				<div class="well" style="padding: 5px 0;">
					<?php echo $this->navigation()->menu()->setUlClass('nav nav-list')->render($this->sidebar); ?>
				</div>
			</div>
			<!--Content-->
			<div class="span9">
				<?php echo $this->layout()->content ?>
			</div>
		</div>
		<!--Bottom-->
		<hr>
		<div>Project &copy; 2012</div>
    </div>

</body>
<?php 
// $this->jQuery()->setLocalPath('/js/jquery.js');
// $this->jQuery()->enable();
// echo $this->jQuery();
$this->headScript()->appendFile('/js/bootstrap-dropdown.js','text/javascript');
echo $this->headScript();
?>
	<!--A supprimer en production-->
<script type="text/javascript">
function destroyLessCache(pathToCss) { // e.g. '/css/' or '/stylesheets/'
	if (!window.localStorage ) {
		return;
	}
	var host = window.location.host;
	var protocol = window.location.protocol;
	var keyPrefix = protocol + '//' + host + pathToCss;
	for (var key in window.localStorage) {
		if (key.indexOf(keyPrefix) === 0) {
			delete window.localStorage[key];
		}
	}
}
destroyLessCache('/less/');
</script>
</html>
