<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    
    <?php echo $this->headTitle(); ?>
    
    <?php echo $this->headLink(); ?>
    <?php //echo $this->headLink()->appendStylesheet('/css/style.css') ?>
	
	<link rel="stylesheet/less" href="/less/bootstrap.less">
	<script src="/js/less.js"></script>

    <link rel="icon" type="image/gif" href="/img/favicon.png"/>

    <!-- google hosted jquery -->
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
	
    <?php echo $this->headScript(); ?>

</head>

<body class="<?php echo $this->bodyClass; ?>">
	<!--TopBar-->
	<div class="navbar">
		<div class="navbar-inner">
			<div class="container">
				<div class='pull-left'>
					<span class="badge badge-warning">&nbsp;&nbsp;</span>
					<span class="badge badge-success">&nbsp;&nbsp;</span>
					<span class="badge badge-info">&nbsp;&nbsp;</span>
					<span class="badge badge-important">&nbsp;&nbsp;</span>
					<span class="badge badge-defaut">&nbsp;&nbsp;</span>
					<h3><a><em>Sur la toile</em></a></h3>
				</div>
				<?php echo $this->navigation()->menu()->setUlClass('nav pull-right')->render($this->menu2); ?>
				<form class="navbar-search pull-right">
					<i class="icon-search icon-white"></i>
					<input type="text" class="search-query" placeholder="rechercher">
				</form>
				<?php echo $this->navigation()->menu()->setUlClass('nav pull-right')->render($this->menu1); ?>
			</div>
		</div>
	</div>
    <div class="container">
		<div class="row">
			<!--LeftBar-->
			<div class="span3">
				<div class="well" style="padding: 5px 0;">
					<?php echo $this->navigation()->menu()->setUlClass('nav nav-list')->render($this->sidebar); ?>
				</div>
			</div>
			<!--Content-->
			<div class="span9">
				<?php echo $this->layout()->content ?>
			</div>
		</div>
		<!--Bottom-->
		<hr>
		<div>Project &copy; 2012</div>
    </div>
	
	
        
            
	
</body>
</html>
